development:
  # Configure available database clients. (required)
  clients:
    default:
      database: rada_reporter_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: rada_reporter_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  # Configure available database clients. (required)
  clients:
    default:
      database: rada_reporter_development
      hosts:
        - localhost:27017
      options:
        user: <%= ENV['MONGO_RADA_REPORTER_USER'] %>
        password: <%= ENV['MONGO_RADA_REPORTER_PASS'] %>
        roles:
          - 'root'
	auth_mech: :scram
	auth_source: rada_reporter_development
  options:
test:
  clients:
    default:
      database: rada_reporter_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

staging:
  clients:
    default:
      database: <%= ENV['MONGO_RADA_REPORTER_DB'] %>
      hosts:
        -  <%= ENV['MONGO_RADA_REPORTER_HOST_1'] %>
      options:
        user: <%= ENV['MONGO_RADA_REPORTER_USER'] %>
        password: <%= ENV['MONGO_RADA_REPORTER_PASS'] %>
        roles:
          - 'dbOwner'
        auth_mech: :scram
        auth_source: rada_reporter
        max_pool_size: 20
        min_pool_size: 2
